import os
import sys
try:
    from pptx import Presentation
except ImportError:
    print("python-pptx not installed. Please install it with: pip3 install python-pptx")
    sys.exit(1)

def add_slide(prs, title, content_bullets):
    # Use the 'Title and Content' slide layout (index 1)
    # The layout index might vary slightly depending on the template, 
    # but index 1 is almost universally "Title and Content"
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    
    # Add title
    if slide.shapes.title:
        slide.shapes.title.text = title
    
    # Add content
    # Find the main body placeholder (usually the second placeholder)
    body_shape = None
    for shape in slide.placeholders:
        if shape.placeholder_format.idx == 1:
            body_shape = shape
            break
            
    if body_shape and body_shape.has_text_frame:
        tf = body_shape.text_frame
        
        for i, bullet in enumerate(content_bullets):
            if i == 0:
                p = tf.paragraphs[0]
            else:
                p = tf.add_paragraph()
            
            if bullet.startswith("  -"):
                p.text = bullet.strip(" -")
                p.level = 1
            else:
                p.text = bullet.strip(" -*")
                p.level = 0

def create_presentation():
    template_path = 'template.pptx'
    
    if not os.path.exists(template_path):
        print(f"Error: Could not find '{template_path}'.")
        print("Please save your blank PowerPoint template as 'template.pptx' in this folder.")
        sys.exit(1)
        
    print(f"Loading template from {template_path}...")
    prs = Presentation(template_path)
    
    # Title Slide (Use the first slide layout)
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    
    # Populate title and subtitle if placeholders exist
    if slide.shapes.title:
        slide.shapes.title.text = "Advanced Protocol Fuzzing for Intrusion Detection Systems"
        
    for shape in slide.placeholders:
        if shape.placeholder_format.idx == 1:  # Subtitle placeholder
            shape.text = "Targeting Deep Parser Logic and State Exhaustion in Snort 3\n\nGenerated by Protocol Fuzzer"
            break

    # Slide 2
    add_slide(prs, "Project Objective", [
        "Goal: Design and implement a custom, high-performance protocol fuzzer to uncover memory corruption and logical vulnerabilities in Snort 3.",
        "Target Areas:",
        "  - Algorithmic Complexity & Infinite Recursion.",
        "  - Memory Leak Amplification & State Exhaustion.",
        "  - Deep Parser Vulnerabilities (Out-of-bounds reads, heap overflows).",
        "Approach:",
        "  - Target a custom Snort 3 build instrumented with AddressSanitizer (ASan).",
        "  - Inject raw, malformed PCAP streams directly into Snort's inspection engine."
    ])

    # Slide 3
    add_slide(prs, "Fuzzer Architecture", [
        "Generator Engine: Crafts raw DNS wire-format packets from scratch instead of relying on standard network libraries, allowing intentional RFC violations.",
        "Mutation Engine: Uses weighted strategy rotation to balance between surface-level bit-flips and deep logical anomalies.",
        "Transport Layer: Wraps payloads in synthetic Ethernet/IPv4/UDP headers and writes them to a POSIX named pipe mimicking a live network stream.",
        "Watchdog Monitor: A background thread that tracks process health, detects hangs, and monitors for RAM bloat."
    ])

    # Slide 4
    add_slide(prs, "Attack Vector 1 - Algorithmic Complexity", [
        "The Theory: IDS engines must parse nested structures. If parsing loops aren't strictly bounded, CPU cycles can be exhausted.",
        "Compression Pointer Loops:",
        "  - Crafted DNS pointers that reference themselves (self_ref), reference each other (mutual), or create long cyclic chains.",
        "  - Goal: Trigger infinite recursion in Snort's name decoder.",
        "Label Flooding:",
        "  - Generated DNS queries with 200+ single-byte labels to stress iteration limits."
    ])

    # Slide 5
    add_slide(prs, "Attack Vector 2 - State Exhaustion", [
        "The Theory: Snort tracks connection states. By spoofing millions of unique connections, we can exhaust the flow table and trigger memory leaks.",
        "Implementation:",
        "  - Randomized the 5-tuple (Source IP, Destination IP, Source Port, Destination Port, Protocol) for every injected packet.",
        "The Breakthrough:",
        "  - Synchronized synthetic PCAP timestamps with real wall-clock time.",
        "  - This forced Snort's internal session clock to advance, properly accumulating parallel sessions until timeouts fired."
    ])

    # Slide 6
    add_slide(prs, "Attack Vector 3 - Deep Parser Fuzzing", [
        "The Shift: Standard DNS queries (QR=0) are heavily tested. The real complexity lies in DNS responses (QR=1).",
        "Targeted Anomalies:",
        "  - RDLENGTH Mismatches: Claiming 512 bytes of data but sending 4 (Heap Buffer Overflows).",
        "  - CNAME Bad Pointers: Offsets pointing far beyond the packet boundary (Out-of-Bounds Reads).",
        "  - Count Mismatches: Header claims 20 answer records, but only 1 exists.",
        "  - Overlapping Records: Compression pointers that land maliciously inside the data payload of previous records."
    ])

    # Slide 7
    add_slide(prs, "Process Lifecycle & Crash Detection", [
        "Overcoming Pipe Deadlocks:",
        "  - Standard stdout/stderr pipes have a 64KB kernel limit. Snort output was deadlocking the fuzzer.",
        "  - Solution: Redirected stdout to /dev/null and implemented a background thread to continuously drain stderr.",
        "Crash Logging:",
        "  - When Snort crashes, the fuzzer catches the exit code.",
        "  - Extracts the AddressSanitizer (ASan) stack trace from the drained stderr.",
        "  - Saves a detailed report mapping the crash back to the exact iteration and fuzzing strategy."
    ])

    # Slide 8
    add_slide(prs, "Key Challenges & Engineering Solutions", [
        "Challenge 1: Live Injection on macOS (lo0 loopback).",
        "  - Issue: macOS loopback uses DLT_NULL, which Snort's DAQ does not support by default.",
        "  - Solution: Engineered a synthetic PCAP pipe wrapper that injects packets as standard Ethernet (DLT_EN10MB) without needing root privileges.",
        "Challenge 2: Snort discarding packets without tracking state.",
        "  - Issue: PCAP packets initially had 0, 0 for timestamps, keeping Snort frozen at epoch time.",
        "  - Solution: Injected dynamic microsecond-accurate timestamps into the PCAP record headers."
    ])

    # Slide 9
    add_slide(prs, "Conclusion & Future Work", [
        "Results: Built a highly resilient, deadlock-free protocol fuzzer capable of sustained million-packet execution loops.",
        "Next Steps:",
        "  - Leave the fuzzer running for extended multi-hour campaigns to let ASan catch deep memory leaks.",
        "  - Extend the generator to target other complex application-layer protocols (e.g., HTTP/2, TLS handshakes).",
        "  - Implement coverage-guided feedback (e.g., connecting it to AFL++)."
    ])

    output_file = 'Protocol_Fuzzer_Presentation.pptx'
    prs.save(output_file)
    print(f"Presentation successfully generated: {output_file}")

if __name__ == '__main__':
    create_presentation()
